FROM apache/airflow:3.0.1
USER root
RUN apt-get update && apt-get install -y curl && \
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
    rm kubectl
USER airflow
COPY airflow-dags/ /opt/airflow/
# COPY airflow-dags/ /opt/airflow/dags/
# COPY airflow-dags/jobs/ /opt/airflow/jobs/
