apiVersion: batch/v1
kind: Job
metadata:
  name: ingestion-job
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
      - name: ingestion
        image: ingestion:latest
        imagePullPolicy: Never
        command: ["python3", "/app/ingestion/ingest_data.py"]
        volumeMounts:
        - name: pipeline-data
          mountPath: /app/ingestion/processed_data
      volumes:
      - name: pipeline-data
        persistentVolumeClaim:
          claimName: pipeline-data
      restartPolicy: Never
